[package]
name = "day01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
uuid = { version = "1.9.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
once_cell = "1.19.0"